nome = (input('Digite seu nome completo: '))
print("O seu nome em maiusculo e", nome.upper())
print("O seu nome em minusculo e", nome.lower())
name = nome.split()
print("O seu nome completo possue {} letras." .format(len(nome) - nome.count(' ')))
print('Seu primeiro nome {} tem {} letras.'.format(name[0],len(name[0])))